# Generated by Django 2.0.1 on 2018-11-25 12:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('status', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Passport',
            fields=[
                ('passport_number', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('father_name', models.CharField(max_length=100)),
                ('dob', models.CharField(max_length=10)),
                ('current_add', models.CharField(max_length=400)),
                ('permanent_add', models.CharField(max_length=400)),
                ('gender', models.CharField(max_length=6)),
                ('phone', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=40)),
            ],
        ),
    ]
