# Generated by Django 2.1.2 on 2018-11-25 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='datee',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='applicant',
            name='dispatch',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='applicant',
            name='ministry',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='applicant',
            name='police',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='status',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
