# Generated by Django 2.1.2 on 2018-11-25 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('passp', '0002_auto_20181125_1714'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applicant',
            old_name='datee',
            new_name='date',
        ),
    ]
